/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_admin;

import Acerca.Ayuda;
import Clientes.*;
import Login.Inicio;
import Maestros.Admin_maestros;
import Pagos.Pagos;
import Usuarios.admin_usuario;
import clases.Consultas;
import conexion_BD.conectar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import pedidos.New_pedidos;
import pedidos.Ver_pedidos;

/**
 *
 * @author Guaman
 */
public class Menu_Admin extends javax.swing.JFrame {
private Ver_pedidos Pedidos;
private Ayuda ayudas;
private New_pedidos pedir;
private admin_usuario usuarios;
private Administracion_clientes clint ;
private Pagos pago ;
private Admin_maestros maest ;





    /**
     * Creates new form Menu_Admin
     */
    public Menu_Admin() {
        initComponents();
        this.setExtendedState(Menu_Admin.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Escritorio = new javax.swing.JDesktopPane();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        menu_nuevo_pedido = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenuItem();
        menu_cliente = new javax.swing.JMenu();
        menu_pedido = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menu_rcliente = new javax.swing.JMenuItem();
        menu_rusuarios = new javax.swing.JMenuItem();
        btn_rmaestros = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menu_admini_usu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_acerca = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(204, 204, 204));
        Escritorio.setForeground(new java.awt.Color(204, 204, 204));
        Escritorio.setPreferredSize(new java.awt.Dimension(673, 800));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/defecto.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de Pedidos");

        Escritorio.setLayer(panelImage1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        menu_archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1426145507__archive.png"))); // NOI18N
        menu_archivo.setText("Archivo");

        menu_nuevo_pedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_nuevo_pedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1426152043_document-new.png"))); // NOI18N
        menu_nuevo_pedido.setText("Nuevo Pedido");
        menu_nuevo_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_nuevo_pedidoActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_nuevo_pedido);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1426290303_padlock-b.png"))); // NOI18N
        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_archivo.add(jMenuItem1);

        menu_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.SHIFT_MASK));
        menu_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1426152007_exit.png"))); // NOI18N
        menu_salir.setText("Salir");
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_salir);

        jMenuBar1.add(menu_archivo);

        menu_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1426145067_Client_Male_Light.png"))); // NOI18N
        menu_cliente.setText("Clientes");
        menu_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_clienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_cliente);

        menu_pedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1426145246_beryl-manager.png"))); // NOI18N
        menu_pedido.setText("Pedidos");
        menu_pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_pedidoMouseClicked(evt);
            }
        });
        menu_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pedidoActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_pedido);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1427237511_Money.png"))); // NOI18N
        jMenu1.setText("Pagos");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/printer.png"))); // NOI18N
        jMenu2.setText("Reportes");

        jMenuItem3.setText("Reportes de Ventas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menu_rcliente.setText("Lista de Clientes");
        menu_rcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rclienteActionPerformed(evt);
            }
        });
        jMenu2.add(menu_rcliente);

        menu_rusuarios.setText("Lista de Usuarios");
        menu_rusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rusuariosActionPerformed(evt);
            }
        });
        jMenu2.add(menu_rusuarios);

        btn_rmaestros.setText("Lista de Maestros");
        btn_rmaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rmaestrosActionPerformed(evt);
            }
        });
        jMenu2.add(btn_rmaestros);

        jMenu3.setText("Pedidos");

        jMenuItem4.setText("Pedidos Entregados");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Pedidos No Entregados");
        jMenu3.add(jMenuItem5);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1426152213_internt_web_technology-02-16.png"))); // NOI18N
        jMenu6.setText("Ajustes");

        menu_admini_usu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menu_admini_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1426152364_user_male-16.png"))); // NOI18N
        menu_admini_usu.setText("Administrar Usuarios");
        menu_admini_usu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_admini_usuMouseClicked(evt);
            }
        });
        menu_admini_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_admini_usuActionPerformed(evt);
            }
        });
        jMenu6.add(menu_admini_usu);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1427313162_Manager.png"))); // NOI18N
        jMenuItem2.setText("Administrar Maestros");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar1.add(jMenu6);

        menu_acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1426146072_stock_help-agent.png"))); // NOI18N
        menu_acerca.setText("Acerca de");
        menu_acerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_acercaMouseClicked(evt);
            }
        });
        menu_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_acercaActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_acerca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_pedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_pedidoMouseClicked
   if(Consultas.estacerrado(Pedidos)){
        Pedidos = new Ver_pedidos();
      Escritorio.add(Pedidos);
            Consultas.centrar(Pedidos);
            Pedidos.show();
             }else{
            JOptionPane.showMessageDialog(this," La ventana pedidos ya esta abierta ","Sistema",JOptionPane.INFORMATION_MESSAGE);
        }    
    }//GEN-LAST:event_menu_pedidoMouseClicked

    private void menu_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pedidoActionPerformed

    }//GEN-LAST:event_menu_pedidoActionPerformed

    private void menu_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_acercaActionPerformed
      
    }//GEN-LAST:event_menu_acercaActionPerformed

    private void menu_acercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_acercaMouseClicked
 if(Consultas.estacerrado(ayudas)){
        ayudas = new Ayuda();
      Escritorio.add(ayudas);
            Consultas.centrar(ayudas);
            ayudas.show();
             }else{
            JOptionPane.showMessageDialog(this," La ventana Acerca de ya esta abierta ","Sistema",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_menu_acercaMouseClicked

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
System.exit(0);
    }//GEN-LAST:event_menu_salirActionPerformed

    private void menu_nuevo_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_nuevo_pedidoActionPerformed
 if(Consultas.estacerrado(pedir)){
        pedir = new New_pedidos();
      Escritorio.add(pedir);
            Consultas.centrar(pedir);
            pedir.show();
             }else{
            JOptionPane.showMessageDialog(this," La ventana Nuevo Pedidos ya esta abierta ","Sistema",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_menu_nuevo_pedidoActionPerformed

    private void menu_admini_usuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_admini_usuMouseClicked
       
    }//GEN-LAST:event_menu_admini_usuMouseClicked

    private void menu_admini_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_admini_usuActionPerformed
        if(Consultas.estacerrado(usuarios)){
        usuarios = new admin_usuario();
      Escritorio.add(usuarios);
            Consultas.centrar(usuarios);
            usuarios.show();
             }else{
            JOptionPane.showMessageDialog(this," La ventana Administracion Usuario ya esta abierta ","Sistema",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_menu_admini_usuActionPerformed

    private void menu_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_clienteMouseClicked
         if(Consultas.estacerrado(clint)){
        clint = new Administracion_clientes();
      Escritorio.add(clint);
            Consultas.centrar(clint);
            clint.show();
             }else{
            JOptionPane.showMessageDialog(this," La ventana Administracion Clientes ya esta abierta ","Sistema",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_menu_clienteMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
        Inicio obj = new Inicio();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
         
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
  if(Consultas.estacerrado(maest)){
        maest = new Admin_maestros();
      Escritorio.add(maest);
            Consultas.centrar(maest);
            maest.show();
             }else{
            JOptionPane.showMessageDialog(this," La ventana Administracion Maestros ya esta abierta ","Sistema",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       if(Consultas.estacerrado(pago)){
        pago = new Pagos();
      Escritorio.add(pago);
            Consultas.centrar(pago);
            pago.show();
             }else{
            JOptionPane.showMessageDialog(this," La ventana Pagos ya esta abierta ","Sistema",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         conectar ccc = new conectar();
     ccc.conexion();       
         String ruta="src\\reportes\\ventas.jasper";
     
          JasperReport jr=null;
       try {
     jr= (JasperReport) JRLoader.loadObjectFromFile(ruta);
     JasperPrint informe =JasperFillManager.fillReport(jr,null,ccc.conexion());
     JasperViewer ventanavisor = new JasperViewer(informe,false);           
 ventanavisor.setTitle("REPORTE DE VENTAS");
 ventanavisor.setVisible(true);
 } catch (JRException ex) {
            Logger.getLogger(Administracion_clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menu_rclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rclienteActionPerformed
         conectar ccc = new conectar();
     ccc.conexion();       
         String ruta="src\\reportes\\ListaClientes.jasper";
     
          JasperReport jr=null;
       try {
     jr= (JasperReport) JRLoader.loadObjectFromFile(ruta);
     JasperPrint informe =JasperFillManager.fillReport(jr,null,ccc.conexion());
     JasperViewer ventanavisor = new JasperViewer(informe,false);           
 ventanavisor.setTitle("Lista de Clientes");
 ventanavisor.setVisible(true);
 } catch (JRException ex) {
            Logger.getLogger(Administracion_clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_rclienteActionPerformed

    private void menu_rusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rusuariosActionPerformed
       conectar ccc = new conectar();
     ccc.conexion();       
         String ruta="src\\reportes\\ListaUsuarios.jasper";
     
          JasperReport jr=null;
       try {
     jr= (JasperReport) JRLoader.loadObjectFromFile(ruta);
     JasperPrint informe =JasperFillManager.fillReport(jr,null,ccc.conexion());
     JasperViewer ventanavisor = new JasperViewer(informe,false);           
 ventanavisor.setTitle("Lista de Usuarios");
 ventanavisor.setVisible(true);
 } catch (JRException ex) {
            Logger.getLogger(Administracion_clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_rusuariosActionPerformed

    private void btn_rmaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rmaestrosActionPerformed
        conectar ccc = new conectar();
     ccc.conexion();       
         String ruta="src\\reportes\\ListaMaestros.jasper";
     
          JasperReport jr=null;
       try {
     jr= (JasperReport) JRLoader.loadObjectFromFile(ruta);
     JasperPrint informe =JasperFillManager.fillReport(jr,null,ccc.conexion());
     JasperViewer ventanavisor = new JasperViewer(informe,false);           
 ventanavisor.setTitle("Lista de Maestros");
 ventanavisor.setVisible(true);
 } catch (JRException ex) {
            Logger.getLogger(Administracion_clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_rmaestrosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
          conectar ccc = new conectar();
     ccc.conexion();       
         String ruta="src\\reportes\\PedidosE.jasper";
     
          JasperReport jr=null;
       try {
     jr= (JasperReport) JRLoader.loadObjectFromFile(ruta);
     JasperPrint informe =JasperFillManager.fillReport(jr,null,ccc.conexion());
     JasperViewer ventanavisor = new JasperViewer(informe,false);           
 ventanavisor.setTitle("Lista de Pedidos Entregados");
 ventanavisor.setVisible(true);
 } catch (JRException ex) {
            Logger.getLogger(Administracion_clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem btn_rmaestros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu_acerca;
    private javax.swing.JMenuItem menu_admini_usu;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_cliente;
    private javax.swing.JMenuItem menu_nuevo_pedido;
    private javax.swing.JMenu menu_pedido;
    private javax.swing.JMenuItem menu_rcliente;
    private javax.swing.JMenuItem menu_rusuarios;
    private javax.swing.JMenuItem menu_salir;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
